import { BIOMES, biomeAt } from '../shared/biomes.js';
import { HOME_WAYSTONE, nearbyWaystone, waystoneSites, awakenedCount } from '../shared/waystones.js';
import type { Player, Snapshot } from '../shared/game.js';
import { CREATURES, bondCount, guardianCount, creatureView } from '../shared/creatures.js';
import { SUPPLIES } from '../shared/forage.js';
const escape = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
/** One cached terrain chart per room seed; current discovery and travel readiness stay live. */
export class ConstellationAtlas {
  private seed = -1; private base = '';
  page: 'map' | 'guide' = 'map';
  render(p: Player, snapshot: Snapshot, tracked?: number) {
    const tabs=`<div class="atlas-tabs" role="tablist" aria-label="Atlas pages"><button class="btn" role="tab" aria-selected="${this.page==='map'}" data-action="atlas-page" data-page="map">Waystone map</button><button class="btn" role="tab" aria-selected="${this.page==='guide'}" data-action="atlas-page" data-page="guide">Field guide · ${bondCount(snapshot.world.bonds)}/4</button></div>`;
    return tabs+(this.page==='guide'?this.guide(p,snapshot):this.chart(p,snapshot,tracked));
  }
  private guide(p:Player,s:Snapshot) {
    const companion=(s.creatures??[]).map(creatureView).find(c=>c.owner===p.id),mask=s.world.bonds??0;
    return `<div class="field-guide" role="tabpanel" aria-label="Field guide"><p>Befriend the Wilds. Aim at a grove creature and press R or tap its prompt to share one favorite supply. Your companion follows you; ask it to scout for fresh patches.</p><div class="guide-progress"><b>${bondCount(mask)}/4 grove friends</b><b>${guardianCount(s.world.guardians)}/8 Wardens freed</b></div>${companion&&companion.kind!==4?`<div class="companion-row"><span>Your companion: <b>${CREATURES[companion.kind].name}</b></span><button class="btn" data-action="release-creature" ${!p.alive||!p.connected||s.phase!=='active'?'disabled':''}>Let it wander</button></div>`:''}<div class="guide-cards">${CREATURES.map((c,k)=>`<article class="guide-card ${mask&1<<k?'befriended':''}" style="--creature-color:${c.color}"><i aria-hidden="true">${c.glyph}</i><div><h3>${c.name}</h3><small>${BIOMES[c.biome].name} · ${mask&1<<k?'Befriended ✓':'Find and befriend'}</small><p>${c.description}</p><button class="btn" data-action="track-creature-food" data-food="${c.food}">Find ${SUPPLIES[c.food].name}</button></div></article>`).join('')}</div><article class="guide-warden"><h3>Shade Wardens</h3><p>Violet guardians rest beside the eight waystone ruins. Challenge one when you are ready. Leave its glowing circle before the pulse, or face the Warden and hold your shield. Strike during recovery to free it and find party supplies.</p><p class="help">Co-op friends help each other and return at the arrival waystone after five seconds if scattered. Your field guide and freed Wardens stay with this world. A new round starts a fresh search for companions.</p></article></div>`;
  }
  private chart(p: Player, snapshot: Snapshot, tracked?: number) {
    const seed = snapshot.world.seed, stones = [HOME_WAYSTONE,...waystoneSites(seed)], mask = snapshot.world.waystones ?? 1, near = nearbyWaystone(p,seed), rest = Math.max(0,Math.ceil(((p.warpReadyAt??0)-snapshot.tick)/60));
    if (this.seed !== seed) {
      this.seed = seed; this.base = '';
      for (let x = -600; x < 600; x += 60) for (let z = -600; z < 600; z += 60) this.base += `<rect x="${x}" y="${z}" width="60" height="60" fill="${BIOMES[biomeAt(x+30,z+30,seed)].leaves}" opacity=".28"/>`;
    }
    const chart = `<svg class="waystone-map" viewBox="-600 -600 1200 1200" role="img" aria-label="Nearby waystone atlas. North is up. White marker is your location."><rect x="-600" y="-600" width="1200" height="1200" fill="#132b32"/>${this.base}${stones.filter(s=>mask&1<<s.id).map(s=>`<path d="M0,-5 L${s.x},${s.z}" stroke="#a4ddd2" stroke-width="2" stroke-dasharray="8 10" opacity=".45"/>`).join('')}${stones.map(s=>`<circle cx="${s.x}" cy="${s.z}" r="${mask&1<<s.id?18:11}" fill="${BIOMES[s.biome].spirit}" opacity="${mask&1<<s.id?1:.35}"/><text x="${s.x+25}" y="${s.z+9}" fill="#e8eddf" font-size="28">${s.id===0?'HOME':s.id}</text>`).join('')}<path d="M0,-18 L13,12 L0,6 L-13,12 Z" fill="#fff" stroke="#142d33" stroke-width="3" transform="translate(${Math.max(-570,Math.min(570,p.x))} ${Math.max(-570,Math.min(570,p.z))}) rotate(${-p.yaw*180/Math.PI})"/><text x="0" y="-550" fill="#e6efdf" font-size="32" text-anchor="middle">NORTH ↑</text></svg>`;
    return `<p>Touch the center of a ruin to awaken its waystone for your whole party. ${p.relics===7 ? rest ? `Travel rests for ${rest}s.` : near ? `Standing at ${escape(near.name)}. Choose an awakened stone to travel.` : 'Stand at an awakened waystone to travel.' : 'Find all three skyshards to unlock Warden travel.'}</p><div class="atlas-layout">${chart}<div class="waystone-list">${stones.map(s=>{const awake=!!(mask&1<<s.id);return `<div class="waystone-row"><i style="background:${BIOMES[s.biome].spirit}">${s.id===0?'⌂':s.id}</i><div><b>${escape(s.name)}</b><small>${awake?'Awakened':'Undiscovered'} · ${Math.round(Math.hypot(s.x-p.x,s.z-p.z))} blocks</small></div><button class="btn" data-action="track-waystone" aria-label="${tracked===s.id?'Tracking':'Track'} ${escape(s.name)}" data-waystone="${s.id}">${tracked===s.id?'Tracked':'Track'}</button>${awake?`<button class="btn gold" data-action="warp" aria-label="Travel to ${escape(s.name)}" data-waystone="${s.id}" ${!p.alive||!p.connected||p.relics!==7||!near||near.id===s.id||rest>0||snapshot.phase!=='active'?'disabled':''}>Travel</button>`:''}</div>`;}).join('')}</div></div><p class="help">${awakenedCount(mask)}/8 ruins awakened · Discoveries last for this arena. White arrow: you. Dotted lines: travel links.${Math.abs(p.x)>600||Math.abs(p.z)>600?' You are beyond this chart; your arrow marks the nearest edge.':''}${tracked!==undefined?' <button class="text-btn" data-action="clear-track">Follow the skyshard trail</button>':''}</p>`;
}
}
