import assert from 'node:assert/strict';
import { Client, type Room } from '@colyseus/sdk';
import { VERSION, EYE, idleInput, type Snapshot, type Input } from '../shared/game.js';
import { CREATURES, WILDLIFE, WARDEN, creatureView, creatureTouch, guardianNests, type CreatureView } from '../shared/creatures.js';
import { Construction, type ConstructionState, type ConstructionChanges } from '../shared/construction.js';
import { Forage, suppliesNear, type ForageState, type ForageChanges } from '../shared/forage.js';
import { saveWorld } from '../shared/world-save.js';
import { navigator, wildRoute } from './navigation.js';

const client=new Client(process.env.TEST_ENDPOINT??'http://127.0.0.1:3107'),rooms:Room[]=[],states=new Map<Room,Snapshot>(),seqs=new Map<Room,number>(),errors=new Map<Room,string[]>(),pings:number[]=[],sizes:number[]=[];
let timer:ReturnType<typeof setInterval>|undefined;
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function until(label:string,check:()=>boolean,seconds=12){const end=Date.now()+seconds*1000;while(!check()){if(Date.now()>end)throw Error(`${label} timed out: ${JSON.stringify([...states.values()].map(s=>({phase:s.phase,players:s.players.map(p=>({id:p.id,realm:p.realm,x:p.x,z:p.z,hp:p.hp})),creatures:s.creatures?.map(creatureView).filter(c=>c.owner||c.kind===4)})))}`);await wait(25);}}
function track(r:Room){rooms.push(r);r.reconnection.enabled=false;const blocks=new Construction(),field=new Forage();errors.set(r,[]);
  r.onMessage('construction',(s:ConstructionState)=>assert(blocks.restore(s)));r.onMessage('constructionChanges',(s:ConstructionChanges)=>assert(blocks.apply(s)));r.onMessage('forage',(s:ForageState)=>assert(field.restore(s)));r.onMessage('forageChanges',(s:ForageChanges)=>assert(field.apply(s)));
  r.onMessage('snapshot',(s:Snapshot)=>{sizes.push(Buffer.byteLength(JSON.stringify(s)));assert((s.creatures?.length??0)<=WILDLIFE.limit);s.world.construction=blocks;s.world.forage=field;states.set(r,s);});r.onMessage('worldRestored',()=>{});r.onMessage('latency',(n:number)=>r.send('latencyAck',n));r.onMessage('pong',(n:number)=>pings.push(Date.now()-n));r.onMessage('actionError',(e:string)=>errors.get(r)!.push(e));r.send('sync');return r;
}
const me=(r:Room)=>states.get(r)!.players.find(p=>p.id===r.sessionId)!;
const creatures=(r:Room)=>(states.get(r)!.creatures??[]).map(creatureView);
const actor=(r:Room,id:string)=>creatures(r).find(c=>c.id===id);
function input(r:Room,changes:Partial<Input>={}){const seq=(seqs.get(r)??me(r).ack)+1;seqs.set(r,seq);r.send('input',{...idleInput(),seq,...changes});}
function heartbeat(r:Room){for(const other of rooms)if(other!==r&&other.connection.isOpen)other.send('ping',Date.now());}
async function walk(r:Room,target:{x:number;z:number},stop=()=>Math.hypot(me(r).x-target.x,me(r).z-target.z)<.6,passage=false){const nav=navigator(),route=me(r).realm==='wilds'?wildRoute(me(r),target,states.get(r)!.world.seed,states.get(r)!.world.construction):undefined;let n=0;
  timer=setInterval(()=>{if(stop()){input(r);return;}const p=me(r);while(route&&n<route.length-1&&Math.hypot(p.x-route[n][0],p.z-route[n][1])<.7)n++;const nearGoal=Math.hypot(p.x-target.x,p.z-target.z)<2.2;const point=route?(n===route.length-1?[target.x,target.z]:route[n]):passage||nearGoal?[target.x,target.z]:nav(p,target);input(r,{yaw:Math.atan2(p.x-point[0],p.z-point[1]),z:1,sprint:true,dash:!!route&&Math.hypot(p.x-point[0],p.z-point[1])>7&&(p.dashCooldown??0)<=0});heartbeat(r);},33);
  try{await until('Ordinary navigation',stop,100);}finally{clearInterval(timer);timer=undefined;input(r);}
}
const face=(r:Room,c:CreatureView)=>({yaw:Math.atan2(me(r).x-c.x,me(r).z-c.z),pitch:Math.atan2(c.y+(c.kind===4?1:.8)-me(r).y-EYE,Math.max(.1,Math.hypot(me(r).x-c.x,me(r).z-c.z)))});
async function approach(r:Room,id:string){timer=setInterval(()=>{const c=actor(r,id);if(!c)return;const d=Math.hypot(me(r).x-c.x,me(r).z-c.z);input(r,{...face(r,c),z:d>2.8?1:0,sprint:d>6});heartbeat(r);},33);try{await until('Approach and aim',()=>creatureTouch(me(r),creatures(r),states.get(r)!.world)?.id===id,20);await wait(100);}finally{clearInterval(timer);timer=undefined;const c=actor(r,id);if(c)input(r,face(r,c));}}
async function enter(r:Room){await walk(r,{x:-26,z:-46});r.send('interact');await until('Open secret door',()=>states.get(r)!.world.doorOpen);await walk(r,{x:-26,z:-65},()=>me(r).realm==='wilds',true);}
try{
  let host=track(await client.create('arena',{name:'Creature explorer',version:VERSION,private:true}));const guest=track(await client.joinById(host.roomId,{name:'Grove friend',version:VERSION}));await until('Two seats',()=>states.get(host)?.players.length===2&&states.get(guest)?.players.length===2);
  // A normal portable save gives a repeatable habitat and pantry, never player poses or actor state.
  const save=saveWorld({seed:7919,doorOpen:false,waystones:1,supplies:[8,8,8],upgrades:0,bonds:0,guardians:0},'Living Wilds');const {blocks,...header}=save;
  host.send('worldRestore',{type:'begin',header,count:blocks.length});host.send('worldRestore',{type:'commit'});await until('Portable world',()=>[host,guest].every(r=>states.get(r)!.world.seed===7919));host.send('mode',{mode:'expedition'});await until('Co-op mode',()=>states.get(host)!.mode==='expedition');
  host.send('ready');guest.send('ready');await until('Ready',()=>states.get(host)!.players.every(p=>p.ready));host.send('start');await until('Start',()=>states.get(host)!.phase==='active');await enter(host);
  await until('Seeded wildlife',()=>creatures(host).some(c=>c.kind!==4));const friend=creatures(host).filter(c=>c.kind!==4).sort((a,b)=>Math.hypot(me(host).x-a.x,me(host).z-a.z)-Math.hypot(me(host).x-b.x,me(host).z-b.z))[0];assert(friend.kind!==4);
  await walk(host,friend,()=>Math.hypot(me(host).x-actor(host,friend.id)!.x,me(host).z-actor(host,friend.id)!.z)<8);await approach(host,friend.id);
  const food=CREATURES[friend.kind].food,stock=states.get(host)!.world.supplies![food],errorCount=errors.get(guest)!.length;
  guest.send('creature',{id:host.sessionId,owner:guest.sessionId,supplies:[999,999,999],position:friend});await until('Forged interaction rejected',()=>errors.get(guest)!.length>errorCount);assert.equal(states.get(host)!.world.supplies![food],stock);
  host.send('creature',{id:guest.sessionId,kind:99,supplies:[999,999,999]});await until('Shared bond',()=>[host,guest].every(r=>actor(r,friend.id)?.owner===host.sessionId));assert.equal(states.get(host)!.world.supplies![food],stock-1);assert.equal(states.get(host)!.world.bonds,1<<friend.kind);assert.equal(me(host).kills,0);
  await until('Companion cadence',()=>states.get(host)!.tick>=(me(host).friendReadyAt??0));await approach(host,friend.id);host.send('creature');await until('Scout event',()=>states.get(host)!.events.some(e=>e.type==='creature_scout'&&e.actor===host.sessionId));const scout=states.get(host)!.events.find(e=>e.type==='creature_scout'&&e.actor===host.sessionId)!;assert(scout.position);assert(suppliesNear(me(host).x,me(host).z,7919,72).some(n=>n.kind===food&&n.x===scout.position!.x&&n.z===scout.position!.z));assert.equal(states.get(host)!.world.supplies![food],stock-1);
  console.log('PASS: ordinary navigation and aim befriended and scouted shared seeded wildlife; identity/stock claims did not control the server');
  await enter(guest);await walk(guest,me(host),()=>Math.hypot(me(guest).x-me(host).x,me(guest).z-me(host).z)<6);await approach(guest,friend.id);const stealErrors=errors.get(guest)!.length;guest.send('creature');await until('Companion protected',()=>errors.get(guest)!.length>stealErrors);assert.equal(actor(host,friend.id)!.owner,host.sessionId);
  const token=host.reconnectionToken,id=host.sessionId;host.connection.close();await until('Disconnect',()=>states.get(guest)!.players.some(p=>p.id===id&&!p.connected));assert.equal(actor(guest,friend.id)!.owner,id);host=track(await client.reconnect(token));await until('Reconnect',()=>states.get(host)?.players.find(p=>p.id===id)?.connected===true&&actor(host,friend.id)?.owner===id);assert.equal(host.sessionId,id);assert.equal(states.get(host)!.world.bonds,1<<friend.kind);
  const nest=guardianNests(7919).sort((a,b)=>Math.hypot(a.x-me(host).x,a.z-me(host).z)-Math.hypot(b.x-me(host).x,b.z-me(host).z))[0];await walk(host,nest,()=>!!actor(host,nest.id)&&Math.hypot(me(host).x-nest.x,me(host).z-nest.z)<6);await approach(host,nest.id);await until('Challenge cadence',()=>states.get(host)!.tick>=(me(host).friendReadyAt??0));
  assert.equal(actor(host,nest.id)!.state,'dormant');assert.equal(me(host).hp,100);const before=[...states.get(host)!.world.supplies!];host.send('creature');await until('Challenge begins',()=>actor(host,nest.id)!.state!=='dormant');
  const startHp=me(host).hp;timer=setInterval(()=>{const c=actor(host,nest.id)!;input(host,{...face(host,c),block:true});heartbeat(host);},33);await until('Visible telegraph',()=>actor(host,nest.id)!.state==='windup');assert(actor(host,nest.id)!.timer>0);await until('Shield blocks real pulse',()=>states.get(host)!.events.some(e=>e.type==='hit'&&e.actor===`wild:${nest.id}`&&e.target===id&&e.blocked),8);clearInterval(timer);timer=undefined;assert.equal(me(host).hp,startHp);
  timer=setInterval(()=>{const c=actor(host,nest.id)!;const d=Math.hypot(me(host).x-c.x,me(host).z-c.z),strike=c.state==='recover'&&d<3.5&&(me(host).cooldown??0)<.04;input(host,{...face(host,c),weapon:'sword',block:!strike,attack:strike,z:d>2.5?1:0});heartbeat(host);},33);
  await until('Guardian freed',()=>[host,guest].every(r=>!!((states.get(r)!.world.guardians??0)&1<<nest.ruin)),40);clearInterval(timer);timer=undefined;input(host);assert.equal(actor(host,nest.id)!.hp,0);assert.equal(actor(host,nest.id)!.state,'cleared');assert.equal(me(host).kills,0);assert(me(host).xp>0);assert.deepEqual(states.get(host)!.world.supplies,before.map((n,k)=>n+[6,6,4][k]));
  console.log('PASS: an optional Warden telegraphed a real shield-blocked pulse; ordinary sword inputs freed it once and replicated supplies and guide progress');
  assert.equal(states.get(host)!.host,guest.sessionId); // Reconnecting preserves a seat; host duties stay with the friend.
  const grown=saveWorld(states.get(host)!.world,'Grove friends and freed Wardens');guest.send('lobby');await until('Return lobby',()=>[host,guest].every(r=>states.get(r)!.phase==='waiting'));assert.equal(states.get(host)!.creatures!.length,0);const {blocks:savedBlocks,...grownHeader}=grown;guest.send('worldRestore',{type:'begin',header:grownHeader,count:savedBlocks.length});guest.send('worldRestore',{type:'commit'});await until('Restored progress',()=>states.get(guest)!.world.title===grown.title);assert.deepEqual(saveWorld(states.get(guest)!.world,grown.title),grown);assert(states.get(guest)!.players.every(p=>!p.ready));
  for(let n=0;n<10;n++){host.send('ping',Date.now());guest.send('ping',Date.now());await wait(50);}const sorted=pings.sort((a,b)=>a-b),p95=sorted[Math.floor(sorted.length*.95)];assert(p95<1000);assert(Math.max(...sizes)<12000);
  console.log(`PASS: companion ownership survived reconnect; portable version ${grown.version} saved discoveries and cleared encounters; peak snapshot ${Math.max(...sizes)} bytes, ping p95 ${p95} ms`);
}finally{clearInterval(timer);await Promise.all(rooms.filter(r=>r.connection.isOpen).map(r=>r.leave()));}
